### ISSUE TITLE
User stories

### ISSUE THREAD

**Issue by tavi22** [tavi22/Reseller-Web#7]
User stories are a way to specify requirements keeping in mind:
 -> who the user is
 -> what the user needs
 -> why the user needs that specific system function

**Comment by StancuDenisaG** [comment]
## Admin

* Can edit/delete accounts and posts so that they can have control over the application

## Unregistered User
* Can register so that they can use the application

## Registered User

* Can log into their account so they can navigate the application

* Can add products to wishlist to highlight their favorite items

* Can edit/delete their account so that they have full control over their own account
* Can search and interact with other accounts so that they have a personalised experience 
* Can recover access if password is lost so that they don't lose their account

## Seller
* Can post a product so that they offer it for sale
* Can accept/refuse/counter an offer so that they can easily communicate with the buyer 

## Buyer
* Can add products to cart so that they can purchase the items
* Can follow seller's profile so that they can see newly posted products
* Can search products and sellers so that they can find the specific item they are looking for
